//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesManagement.Application.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoviesManagement.Application.Common.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured while adding the movie.
        /// </summary>
        internal static string MovieCannotBeAdded {
            get {
                return ResourceManager.GetString("MovieCannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description you have entered must be less than 255 characters.
        /// </summary>
        internal static string MovieDescriptionLengthMustBeShorterThan255 {
            get {
                return ResourceManager.GetString("MovieDescriptionLengthMustBeShorterThan255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description you have entered should not be an empty.
        /// </summary>
        internal static string MovieDescriptionShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("MovieDescriptionShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name you have entered must be less than 50 characters.
        /// </summary>
        internal static string MovieNameLengthMustBeShorterThan50 {
            get {
                return ResourceManager.GetString("MovieNameLengthMustBeShorterThan50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name you have entered should not be an empty.
        /// </summary>
        internal static string MovieNameShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("MovieNameShouldNotBeEmpty", resourceCulture);
            }
        }
    }
}
